"""add signature to UserData

Revision ID: a784fb4ebbb6
Revises: e155ef2e72ef
Create Date: 2025-05-30 10:00:58.845887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a784fb4ebbb6'
down_revision = 'e155ef2e72ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('signature', sa.String(length=256), nullable=True))
    op.alter_column('user_data', 'data_content',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_data', 'data_content',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=False)
    op.drop_column('user_data', 'signature')
    # ### end Alembic commands ###
