"""add expires_at to DataAuthorization

Revision ID: e155ef2e72ef
Revises: 
Create Date: 2025-05-22 20:47:13.206602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e155ef2e72ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_authorization', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_authorization', 'expires_at')
    # ### end Alembic commands ###
